TASK_5
BolshakovNO/pt-study pull request #1
Opened 2023-12-20 19:04 UTC by GYelejin

modified:   service/modules/api/files.py
	modified:   service/modules/api/users.py
    modified:   service/modules/models/users.py
	modified:   service/modules/services/file_storage.py
	modified:   tests/api/test_users.py

2023-12-24 07:34 UTC, BolshakovNO requested changes

2023-12-24 07:34 UTC, BolshakovNO commented on service/modules/api/files.py
> +# Configure Minio client
плохая практика объявлять клиенты и настройки на уровне модуля с API

если клиент понадобится где-то еще, будет очень с транно импортировать отсудя. Хорошо было бы сделать фабрику которая генерирует соединения

2023-12-24 07:34 UTC, BolshakovNO commented on service/modules/services/file_storage.py
> +        self.minio_client = Minio(
а в чем тогда был смысл передавать клиент в АПИ?

2023-12-24 07:34 UTC, BolshakovNO commented on service/modules/services/file_storage.py
>      async def download(self, username: str, filename: str) -> AsyncIterable[bytes]:
раз тут нет в аргументах клиента, странно  что не словил ошибку

2023-12-26 11:09 UTC, GYelejin commented on service/modules/services/file_storage.py
> +        self.minio_client = Minio(
это ошибка. Спешил и не удалил из АПИ.

2025-03-04 12:42 UTC, closed without merging